Implemented signers
zksync-sdk/zksync-swift pull request #1
Opened 2021-01-13 16:58 UTC by belyakove

2021-01-13 17:35 UTC, popzxc reviewed
Do all the dependencies have to be a part of the repository, or is it a `.gitignore` issue?

2021-01-17 10:17 UTC, belyakove commented
> Do all the dependencies have to be a part of the repository, or is it a `.gitignore` issue?

They don't necessarily need to be in repository. They are there just to be able to run example app right away without need to run `pod install`. They can be removed from repo and put to `.gitignore` if needed. Please let me know how do you prefer

2021-01-17 12:02 UTC, popzxc commented
I think less code in the repository is desirable, thus I'd suggest getting rid of it.

2021-01-17 20:33 UTC, belyakove commented
> I think less code in the repository is desirable, thus I'd suggest getting rid of it.

Removed Pods from repo

2021-01-18 09:25 UTC, belyakove commented
Can this one be merged?

2021-01-18 09:31 UTC, popzxc commented
@StanislavBreadless Please review this PR and merge if it satisfies requirements.

2021-01-19 19:10 UTC, StanislavBreadless requested changes
Hi :slightly_smiling_face:, I have a few questions:

2021-01-20 16:19 UTC, belyakove commented on .gitignore
>  # `pod install` in .travis.yml
This is only applicable if you are using github CI

2021-01-20 16:23 UTC, belyakove commented on ZKCryptoSDK/Classes/ZKCryptoSDK.swift
> +public class ZKCryptoSDK: NSObject {
It should be possible to use it as a separate pod. Was planning to look at the project structure as the final step

2021-01-20 16:24 UTC, belyakove commented on ZKSyncSDK/Classes/Signer/Utils/Utils.swift
> +        exponent = BigUInt(expBase).power(Int(exponent))
Indeed Int can be used here. Will update

2021-01-20 16:38 UTC, closed without merging